### ISSUE TITLE
Percentage of difference 

### ISSUE THREAD

**Issue by EEvil-G** [avh4/imagecomparison#7]
Can i compare two given images and print the percentage of difference between them?

**Comment by avh4** [comment]
No, currently it will immediately fail if any pixels don't match.  If you're looking to make modifications, you can find the relevant code here: https://github.com/avh4/imagecomparison/blob/master/imagecomparison/src/main/java/net/avh4/util/imagecomparison/ImageComparison.java#L69-L92

I haven't worked with Java in about 5 years, so feel free to fork and do what you like with it -- everything in this repo can be considered under the [MIT license](https://opensource.org/licenses/MIT).

**Comment by EEvil-G** [comment]
okay, i get it.Thanks for ur reply
